# Generated by Django 5.2.6 on 2026-01-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='content',
            field=models.TextField(default='Pamela Robinson is a keynote speaker, corporate and leadership trainer, founder of Fusion Force and a recognized expert in sales and marketing support for hospitality companies.', help_text='Format your content like this:\n        \n        **BOLD TITLE HERE**\n        This is the paragraph text that goes under the bold title.\n        You can have multiple lines here.\n        \n        **ANOTHER BOLD TITLE**\n        Another paragraph here with more details.\n        Multiple lines are supported.\n        \n        • Bullet point 1\n        • Bullet point 2\n        • Bullet point 3\n        \n        Use **double asterisks** for bold titles.\n        Use • for bullet points.\n        Leave empty line between sections.'),
        ),
    ]
