# Generated by Django 5.2.6 on 2026-01-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_aboutsection_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Second image that appears when content is long (3+ sections)', null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='content',
            field=models.TextField(default='Pamela Robinson is a keynote speaker...', help_text='Format your content like this:\n        \n        **BOLD TITLE HERE**\n        This is the paragraph text...\n        \n        **ANOTHER BOLD TITLE**\n        Another paragraph here...\n        \n        • Bullet point 1\n        • Bullet point 2'),
        ),
    ]
