# Generated by Django 5.2.6 on 2026-01-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aboutsection_image_2_alter_aboutsection_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeEbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Free Leadership Guide', max_length=200)),
                ('subtitle', models.CharField(default='Download our free guide to leadership excellence', max_length=300)),
                ('description', models.TextField(default='Get our exclusive free eBook with leadership insights, strategies, and actionable tips from Pamela Robinson.', help_text='Description shown to users before download')),
                ('ebook_file', models.FileField(blank=True, null=True, upload_to='ebooks/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='ebook_covers/')),
                ('is_active', models.BooleanField(default=True)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Free eBook',
                'verbose_name_plural': 'Free eBooks',
            },
        ),
    ]
